let dice1 = Math.floor((Math.random() * 900) + 100);
console.log(dice1);
let dice2 = Math.floor((Math.random() * 900) + 100);
console.log(dice2);
let dice3 = Math.floor((Math.random() * 900) + 100);
console.log(dice3);
let dice4 = Math.floor((Math.random() * 900) + 100);
console.log(dice4);
let dice5 = Math.floor((Math.random() * 900) + 100);
console.log(dice5);
let add = (dice1+dice2+dice3+dice4+dice5);
console.log(add);
let avg = add/5;
console.log(avg);